#!/usr/bin/env bash
# This script transfers a file from the client to a server

# Check if the number of arguments passed is less than 4
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
FILE=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

# Transfer the file to the user's home directory on the server
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME@$SERVER_IP:~/"

