#!/usr/bin/env bash
# This script creates a PID file, displays messages, and handles signals.

# Function to handle SIGTERM and SIGQUIT signals
handle_sigterm() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}

# Function to handle SIGINT signal
handle_sigint() {
    echo "Y U no love me?!"
}

# Trap signals and call the corresponding functions
trap 'handle_sigterm' SIGTERM SIGQUIT
trap 'handle_sigint' SIGINT

# Create PID file
echo $$ > /var/run/myscript.pid

# Infinite loop to display messages
while true
do
    echo "To infinity and beyond"
    sleep 1
done
