#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process.

# Find the process ID (PID) of 4-to_infinity_and_beyond
PID=$(pgrep -f "4-to_infinity_and_beyond")

if [[ -n $PID ]]; then
    # If the PID is not empty (process exists), kill it
    kill $PID
else
    echo "4-to_infinity_and_beyond process not found."
fi
