#!/usr/bin/env bash
# This script displays the content of the current directory in a list format

for file in *; do
    # Check if the file is not hidden and contains a dash
    if [[ ! $file == .* && $file == *-* ]]; then
        # Extract the part of the name after the first dash
        echo "${file#*-}"
    fi
done

